services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
      - 3050:3050
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    working_dir: /workspace
    networks:
      - local

networks:
  local:
    external: true
